export default () => {
  const postArray =[
    {
      id: 0,
      AuthorName: "Michael Kaiser",
      SenderName: "Kate Katey",
      Type: 0,
      Caption: "Look at this cool thing!",
      Content: "this is a coolest picture",
      RightCounter: 30,
      CurrentPost: true,
      UserId: 0,
    },
    {
      id: 1,
      AuthorName: "Json Johnson",
      SenderName: "Ruby Makhol",
      Type: 1,
      Caption: "Ohhh yeah json in the house",
      Content: "this is a cool text post",
      RightCounter: 5,
      CurrentPost:true,
      UserId: 1,
    },
    {
      id: 2,
      AuthorName: "zozo",
      SenderName: "Json Johnson",
      Type:2,
      Caption: "Noooooo he is sick",
      Content: "https://www.Imacoolguy.com",
      RightCounter: 101,
      CurrentPost: true,
      UserId: 2,
    },
    {
      id: 4,
      AuthorName: "Michael Kaiser",
      SenderName: "Ruby Makhol",
      Type: 0,
      Caption: "Look at this cool thing!",
      Content: "this is a coolest picture",
      RightCounter: 50,
      CurrentPost: false,
      UserId: 0,
    },
    {
      id: 5,
      AuthorName: "Json Johnson",
      SenderName: "Ruby Makhol",
      Type: 1,
      Caption: "ggggggggg",
      Content: "zzzzzzzzzz",
      RightCounter: 5,
      CurrentPost:true,
      UserId: 1,
    },
    {
      id: 6,
      AuthorName: "zozo",
      SenderName: "Json Johnson",
      Type:2,
      Caption: "YESSS he is sick",
      Content: "https://www.Imacoolguy.com",
      RightCounter: 5000,
      CurrentPost: true,
      UserId: 2,
    },
    {
      id: 7,
      AuthorName: "Michael Kaiser",
      SenderName: "Ruby Makhol",
      Type: 0,
      Caption: "Look at this cool thing!",
      Content: "this is a coolest picture",
      RightCounter: 42,
      CurrentPost: false,
      UserId: 0,
    },
  ];
  return postArray;
}
